name: CMake

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: test

    steps:
      - uses: actions/checkout@v2

      - name: Make build directory
        run: mkdir build && cd build
        working-directory: test

      - name: Configure CMake
        run: cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        working-directory: test/build

      - name: Build (MultiByte)
        run: cmake --build . --config ${{env.BUILD_TYPE}} -- /p:CharacterSet=MultiByte
        working-directory: test/build

      - name: Test (MultiByte)
        working-directory: ${{github.workspace}}/test/build
        run: ctest -C ${{env.BUILD_TYPE}} --verbose

      - name: Build (Unicode)
        run: cmake --build . --config ${{env.BUILD_TYPE}} -- /p:CharacterSet=Unicode
        working-directory: test/build

      - name: Test (Unicode)
        working-directory: ${{github.workspace}}/test/build
        run: ctest -C ${{env.BUILD_TYPE}} --verbose
